version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly" # Less frequent for book projects
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
