# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # General code quality and formatting
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-toml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: debug-statements
      - id: check-docstring-first
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-ast
      - id: check-builtin-literals
      - id: check-executables-have-shebangs
      #- id: name-tests-test
      #  args: ['--pytest-test-first']

  # Ruff - Modern Python linter and formatter
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
        files: ^(src/|tests/).*\.py$
      # Run the formatter
      - id: ruff-format
        files: ^(src/|tests/).*\.py$

  # MyPy type checking
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.0
    hooks:
      - id: mypy
        files: ^(src/|tests/).*\.py$
        additional_dependencies:
          - pydantic>=2.11.0
          - fastapi>=0.115.0
          - sqlmodel>=0.0.24
          - types-PyYAML
        args: [--ignore-missing-imports, --no-strict-optional]

  # Security scanning with bandit
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
      - id: bandit
        files: ^src/.*\.py$
        args: ["-r", "src/", "-f", "json", "-o", "bandit-report.json"]

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:
      - id: markdownlint
        args: ["--fix"]

  # YAML and JSON formatting with prettier
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        types_or: [yaml, json, markdown]

  # Jinja2/HTML template linting
  - repo: https://github.com/thibaudcolas/curlylint
    rev: v0.13.1
    hooks:
      - id: curlylint
        files: ^(src/|tests/).*\.(html|jinja|jinja2|j2)$
        args: ["--parse-only"]

# Configuration for pre-commit.ci (if using)
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false
